### ISSUE TITLE
Replacement battery specs

### ISSUE THREAD

**Issue by philips** [Takiiiiiiii/Miyoo-Mini#6]
Do you know what the battery model is? I have seen reviews say it is Samsung style but I can't figure out the exact model.

**Comment by philips** [comment]
Ah found on Reddit https://www.reddit.com/r/MiyooMini/comments/rzigb7/confirmed_by_e1000_on_discord_as_a_functional/

**Comment by rooneysh** [comment]
You can buy Samsung w2013 battery.
