### ISSUE TITLE
New SD Card

### ISSUE THREAD

**Issue by painscough** [Takiiiiiiii/Miyoo-Mini#8]
I am trying to add a new SD card to my miyoo mini to expand storage.  The roms do not show up in the game list though.  I have copied everything over from the original sd card, refresh the roms list, and none of them show.  If I put the original card back in they all show.  What am I missing here?  What is the proper process to change the SD card?  I tried following the Read me files for the Prepared SD card and the upgrade but the same issue happens no matter what I do.  I have spent days on this and can't figure it out, any help would be greatly appreciated.

**Comment by Takiiiiiiii** [comment]
It sounds like you are not using the folder structure that I made for this repo. For example, your NES games would need to be in `/Roms/nes`

If you do that, your issues will be fixed. All the directories are listed on the readme page for this repo. You can make these folders manually, or you can use the SD files: https://github.com/Takiiiiiiii/Miyoo-Mini/releases/download/v1.0SD/miyoo.mini_v1.0.7z

**Comment by painscough** [comment]
Thank you for the update.  I thought I did this, but I will double check everything again when I get off of work and update.  

Thanks again.

**Comment by painscough** [comment]
I renamed the folder on the new SD card per the readme file.  FC = nes, SFC = snes, etc.  The only one that shows on the new sd card after refreshing the roms list is mame2003.  I use the exact same rom files as the orginal SD card.  

The new sd card is a SAMSUNG EVO Select found here: https://www.amazon.com/gp/product/B09B1JFY24/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1

Are there any known issues with this SD card?  I have it formatted as FAT32.

**Comment by Takiiiiiiii** [comment]
It seems like you do not have the files from my SD card package on the root of your card. 

Discussed here: https://youtu.be/okAe8kBvOHA?t=412

**Comment by painscough** [comment]
This did it.  I am not sure what I was missing exactly but it is working now.  Thank you for all your help!
